In [2]:
#Create a pandas DataFrame using the employee data provided below
import pandas as pd

data = {
    "EmployeeID": [201,202,203,204,205,206,207,208,209,210],
    "Name": ["Sarah","Michael","Jennifer","David","Lisa","James","Emma","Robert","Sophia","William"],
    "Department": ["Engineering","Sales","Marketing","Engineering","HR","Sales","Engineering","Marketing","Sales","HR"],
    "Salary": [85000,62000,71000,92000,58000,68000,78000,75000,65000,60000],
    "Performance Score": [4,3,5,5,4,4,3,4,5,3],
    "Years of Service": [5,3,7,8,4,6,2,5,4,3]
}

employees_df = pd.DataFrame(data)
print(employees_df)

   EmployeeID      Name   Department  Salary  Performance Score  \
0         201     Sarah  Engineering   85000                  4
1         202   Michael        Sales   62000                  3
2         203  Jennifer    Marketing   71000                  5
3         204     David  Engineering   92000                  5
4         205      Lisa           HR   58000                  4
5         206     James        Sales   68000                  4
6         207      Emma  Engineering   78000                  3
7         208    Robert    Marketing   75000                  4
8         209    Sophia        Sales   65000                  5
9         210   William           HR   60000                  3

   Years of Service
0                 5
1                 3
2                 7
3                 8
4                 4
5                 6
6                 2
7                 5
8                 4
9                 3

In [3]:
#2 Select only Name, Department, Salary
employees_df[['Name','Department','Salary']]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

In [4]:
#3 Use iloc to display employee at row position 3
employees_df.iloc[3]

EmployeeID                   204
Name                       David
Department           Engineering
Salary                     92000
Performance Score              5
Years of Service               8
Name: 3, dtype: object

In [5]:
#4 Use loc to display employee with EmployeeID 203
employees_df.set_index('EmployeeID').loc[203]

Name                  Jennifer
Department           Marketing
Salary                   71000
Performance Score            5
Years of Service             7
Name: 203, dtype: object

In [6]:
#5 Employees from Engineering department
employees_df[employees_df['Department'] == 'Engineering']

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

In [7]:
#6 Employees with Salary > 70000
employees_df[employees_df['Salary'] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

In [8]:
#7 Sales employees with Performance Score ≥ 4
employees_df[
    (employees_df['Department'] == 'Sales') &
    (employees_df['Performance Score'] >= 4)
]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

In [9]:
# 8 Sort by Salary (Descending) and show top 3 highest paid employees
employees_df.sort_values('Salary', ascending=False).head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

In [10]:
#9 Sort by Department then Salary (descending within each department)
employees_df.sort_values(
    ['Department','Salary'],
    ascending=[True, False]
)

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3